### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mrtpcet** [steevev/senscritique2letterboxd#1]
Hello, when i try to use the script, i obtain this error code : 
```
python ./main.py --username gateau --output movies.csv --add_tv  
File "./main.py", line 11
    def is_valid_profile(username: str) -> bool:
SyntaxError: invalid syntax
```
or 

```
python3 ./main.py --username gateau --output movies.csv --add_tv
Checking your username (gateau)...
Traceback (most recent call last):
  File "/Users/Martin/Downloads/senscritique2letterboxd-main/./main.py", line 236, in <module>
    if not is_valid_profile(p_args.username):
  File "/Users/Martin/Downloads/senscritique2letterboxd-main/./main.py", line 19, in is_valid_profile
    with urllib.request.urlopen(USER_URL % username) as f:
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

**Comment by mrtpcet** [comment]
Last try : 
```
python3 ./main.py --username petitgateau --output movies.csv --add_tv
Traceback (most recent call last):
  File "/Users/Martin/Downloads/senscritique2letterboxd-main/./main.py", line 3, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

But i install lxml on macos : 
```
pip install lxml
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: lxml in /usr/local/lib/python3.9/site-packages (4.9.1)
```

**Comment by steevev** [comment]
The HTTP Error 403 should be fixed now since I set a different user agent. Sorry I cannot replicate the `lxml` module error, maybe try to use `pip3` instead of `pip` when installing requirements ?

However since senscritique redesigned the whole website this script probably does not work anymore. If I have some time I'll try to update it.

Thank you for reporting the errors!

**Comment by steevev** [comment]
[45ac295](https://github.com/steevev/senscritique2letterboxd/commit/45ac2958657644e8546586f84a5f8cc268cad4cf) works with new Senscritique page
